name = "auditready-hr"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "eluon_hr"
database_id = "368c654e-da54-4669-bc3d-196a7f6d620a"
